### ISSUE TITLE
【现场运行】-【车检查清单】来自#72

### ISSUE THREAD

**Issue by liyunfei0302** [CAACES/issues#138]
【编辑】页中，“机坪设备种类”的所有种类都有“车辆到位时间”字段（也就是说所有类型的车，都有“车辆到位时间”字段），而在列表页中，有“摆渡车到位时间”字段，该字段应该是多余的；而且【查询】中也有“摆渡车到位时间”字段，同样是没有必要的。

**Comment by ShiJunXia123** [comment]
在用户所提需求中，如果车辆类型选择了摆渡车，那么需要有车辆到位时间、第一辆摆渡车到位时间、第二辆摆渡车到位时间，目前字段只有一个，统一写成摆渡车到位时间
