### ISSUE TITLE
“详情”时，部分字段不显示

### ISSUE THREAD

**Issue by liyunfei0302** [CAACES/issues#14]
![default](https://user-images.githubusercontent.com/30078196/32824542-57d3b324-ca1c-11e7-8946-fbc58cd63b83.jpg)

**Comment by liyunfei0302** [comment]
【机坪设备巡检】，“详情”时【检查组信息】的“编号”、“巡检人”不显示；“编辑”时正常

**Comment by ShiJunXia123** [comment]
已修复

**Comment by liyunfei0302** [comment]
确认修改，关闭issues
