### ISSUE TITLE
野生动物下的鸟网维护详情界面缺少字段

### ISSUE THREAD

**Issue by chenkuangAmber** [CAACES/issues#17]
野生动物下的鸟网维护详情界，缺少“区域”与“地区”对应不上，缺少“创建人”，“创建时间”，“最后修改人”，“最后修改时间”，等字段

**Comment by ShiJunXia123** [comment]
所有模块创建人创建时间，最后修改人，最后修改时间均不显示在详情表中

**Comment by chenkuangAmber** [comment]
查询界面，编辑界面，详情界面，的字段为地区，列表上的字段为区域，建议统一
