### ISSUE TITLE
目视助航设备管理下的灯光设备的查询

### ISSUE THREAD

**Issue by chenkuangAmber** [CAACES/issues#22]
目视助航设备管理下的灯光设备的查询功能下的灯光类型应假如一个空项，与状态一致
![qq 20171115161808](https://user-images.githubusercontent.com/31473119/32825627-9c439be2-ca20-11e7-9776-544213e9c978.png)

**Comment by chenkuangAmber** [comment]
“假如”改为“加入”

**Comment by ShiJunXia123** [comment]
已修复
