### ISSUE TITLE
【场道管理】-【巡检】-【跑道徒步巡检记录】

### ISSUE THREAD

**Issue by liyunfei0302** [CAACES/issues#39]
1.在“编辑”时，当点击“ 跑道徒步损坏情况关系”的“现场运行”、“问题表示类型”的标签（也就是Label）时页面会向上滚动
2.“跑道徒步标志清晰程度关系:”和“跑步徒步检查明细项情况表:”的“经纬度坐标”在详情时没有值，但在“编辑”时有值
3.“跑道徒步标志清晰程度关系:”的“详情情况”在“详情”和“编辑”时都没有值，在发出的请求中应该是没有该字段

**Comment by ShiJunXia123** [comment]
已修改

**Comment by liyunfei0302** [comment]
确认修改，关闭issues
