### ISSUE TITLE
此字段修改后保存依然是user的名字，有必要在编辑此字段吗？.png

### ISSUE THREAD

**Issue by liyunfei0302** [CAACES/issues#4]
![user](https://user-images.githubusercontent.com/30078196/32823362-e397d304-ca17-11e7-86bb-3928cbedea90.png)

**Comment by ShiJunXia123** [comment]
已修复

**Comment by liyunfei0302** [comment]
此处提交错误，问题是在“机坪设备巡检”，已确认解决，关闭issue
