### ISSUE TITLE
一揽子“服务器错误”

### ISSUE THREAD

**Issue by liyunfei0302** [CAACES/issues#94]
现象：
1.进入界面报“服务器错误”，但可以进入页面
2.点击“新建”按钮报“服务器错误”，但可以打开页面
3.“新建”页面点击“保存”报“服务器错误”并且无法创建

出错模块：
【基础信息管理】-【野生动物设置】-【机场虫类数据库】
【场道管理】-【嵌缝料管理】-【嵌缝料】

**Comment by tzweilai** [comment]
已解决，待发布
