### ISSUE TITLE
一揽子标签不合理

### ISSUE THREAD

**Issue by liyunfei0302** [CAACES/issues#99]
【机坪管理】-【机坪设备】-“详情”的两个“本地坐标”改为“本地坐标P、H”
	【现场运行】-【违章记录】-“详情”没有“本地坐标P、H”，并且最下方的“违章区域坐标”删除
	【现场运行】-【违章记录】-“详情”的“违章标记”的两个“本地坐标”改为“本地坐标P、H”
	【场道管理】-【道面管理】-【场道区域管理】-“详情”的“场道标记”的两个“本地坐标”改为“本地坐标P、H”
	【场道管理】-【巡检】-【道面巡检】-“详情”的两个“本地坐标”改为“本地坐标P、H”
	【场道管理】-【巡检】-【跑道巡检】-“详情”的“跑道道路标志清晰度表”的两个“本地坐标”改为“本地坐标P、H”

**Comment by liyunfei0302** [comment]
待新版本发布
【现场运行】-【违章记录】-“详情”没有“本地坐标P、H”，并且最下方的“违章区域坐标”删除
【场道管理】-【巡检】-【道面巡检】-“详情”的两个“本地坐标”改为“本地坐标P、H”

**Comment by ShiJunXia123** [comment]
已修复
